---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: harbor.aws.59s.io/59s/alpine-worker
params:
  GITHUB_USERNAME:
  GITHUB_PASSWORD:
  CONCOURSE_URL:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:
  CONCOURSE_TEAM:
inputs:
- name: source
- name: repo
run:
  path: /bin/sh
  args: 
  - source/ci/tasks/set-pipelines.sh